export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const SET_INGREDIENTS = "SET_INGREDIENTS";
export const FAIL_INGREDIENTS = "FAIL_INGREDIENTS";

export const PURCHASE_START = "PURCHASE_START";
export const PURCHASE_SUCCESS = "PURCHASE_SUCCESS";
export const PURCHASE_FAIL = "PURCHASE_FAIL";
export const PURCHASE_INIT = "PURCHASE_INIT";

export const FETCH_ORDER_START ='FETCH_ORDER_START'; 
export const FETCH_ORDER_SUCCESS ='FETCH_ORDER_SUCCESS';
export const FETCH_ORDER_FAIL ='FETCH_ORDER_FAIL';
 
